### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by luckypoem** [travisred/comanche#1]
1. the published posts are not arranged as per the order of time.
   in my site: http://surmount.biz.st:2010/,
   the post http://surmount.biz.st:2010/test3 is published after the post http://surmount.biz.st:2010/test2,but in the site,
   the post http://surmount.biz.st:2010/test3 is below
   the post http://surmount.biz.st:2010/test2,
   how to make the post http://surmount.biz.st:2010/test3 is above
   the post http://surmount.biz.st:2010/test2 ??
2. i published 5 posts+your old post (how to use comanche),there is totally 6 posts,but in the homepage of http://surmount.biz.st:2010/,there is no page number link displayed.how to fix it?
   this means "front_page_count: 5" in the config.txt has no effect at all?

**Comment by luckypoem** [comment]
hi,
about question 2,i see."front_page_count: 5"  means there is only 5 posts displayed on the homepage.the other posts are hidden in the "archive" link.

**Comment by luckypoem** [comment]
so how to make pagination for the blog?

**Comment by travisred** [comment]
> how to make the post http://surmount.biz.st:2010/test3 is above
> the post http://surmount.biz.st:2010/test2 ??

The posts are sorted by their dates in descending order: https://github.com/travisred/comanche/blob/63c6643c6457953d5727b17dfb2b337003190ec0/comanche.php#L33

The date should be on the second line of your md files in the format of YYYY-MM-DD.

> about question 2,i see."front_page_count: 5" means there is only 5 posts displayed on the homepage.the other posts are hidden in the "archive" link.

Correct.

> so how to make pagination for the blog?

Fork the repo and modify it. Pagination is not a feature of this version.
